framework: ["terraform", "github_actions", "dockerfile", "ansible"]
quiet: true

# Skip checks that are false positives or have valid exceptions
skip-check:
  # CKV2_ANSIBLE_1: HTTP is acceptable for localhost health checks (no network exposure)
  - CKV2_ANSIBLE_1
