---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  labels:
    app: monitoring
    managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project this application belongs to
  project: homelab

  # Source repository configuration
  source:
    repoURL: https://github.com/iso-st3ph/homelab-devops.git
    targetRevision: main
    path: kubernetes/monitoring

  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  # Sync policy
  syncPolicy:
    automated:
      prune: true      # Delete resources that are no longer in Git
      selfHeal: true   # Force sync when cluster state differs from Git
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true  # Create namespace if it doesn't exist
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore differences in certain fields
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
